services:
  kanbanservice:
    image: ghcr.io/nitishunvi/kanbanboardservice:latest
    container_name: kanbanservice
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      databaseName: KanbanDB
      databaseUsername: postgres
      databasePassword: "Unv!@2000"
      databaseHost: postgres
    restart: unless-stopped
    networks:
      - web

  kanban-app:
    image: ghcr.io/nitishunvi/kanban-board-app:latest
    container_name: kanban-app
    restart: unless-stopped
    networks:
      - web

  postgres:
    image: postgres:16-alpine
    container_name: kanban-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: KanbanDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Unv!@2000
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web

  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --providers.file.filename=/etc/traefik/dynamic.yaml
    ports:
      - "443:443"        # Public port
      - "8080:8080"      # Traefik dashboard (optional)
    volumes:
      - ./dynamic.yaml:/etc/traefik/dynamic.yaml
    networks:
      - web

volumes:
  postgres_data:

networks:
  web:
    driver: bridge