name: Build main

on:
 push:
  branches: 
   - main
 pull_request:
  branches: 
   - main
 workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: Setup dotnet 10.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x
      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version
      
      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: |
         SERVICE_PROJECT=$(echo **/*.Service.csproj)
         echo "SERVICE_PROJECT=$SERVICE_PROJECT" >> $GITHUB_ENV
         dotnet build "$SERVICE_PROJECT" --no-restore --configuration Release
      
      - name: Run Tests
        run: dotnet test **/*.Test.csproj --no-build --configuration Release

      - name: Publish Project
        run: dotnet publish "$SERVICE_PROJECT" --configuration Release --runtime linux-x64 --self-contained false --output publish

      - name: Debug github.actor
        run: |
          echo "Triggered by: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}",
          echo "token: ${#GH_TOKEN}"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GIT_HUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
         context: .
         file: ./service/Dockerfile   # path to your Dockerfile
         push: true                   # pushes image to registry
         tags: ghcr.io/${{ github.repository_owner }}/myservice:latest
